export const USER_ROLE_RELATIONSHIP_OFFICE_COORDINATOR = "USER_ROLE_RELATIONSHIP_OFFICE_COORDINATOR"
export const USER_ROLE_RELATIONSHIP_OFFICE = "USER_ROLE_RELATIONSHIP_OFFICE"
export const USER_ROLE_TECHNICAL_SUPPORT = "USER_ROLE_TECHNICAL_SUPPORT"
export const USER_ROLE_TECHNICAL_SUPPORT_COORDINATOR = "USER_ROLE_TECHNICAL_SUPPORT_COORDINATOR"
export const USER_ROLE_SALES_OPERATIONAL_CO_LEAD = "USER_ROLE_SALES_OPERATIONAL_CO_LEAD"
export const USER_ROLE_SALES_OPERATIONAL_LEAD = "USER_ROLE_SALES_OPERATIONAL_LEAD"
export const USER_ROLE_BUSINESS_SUPPORT = "USER_ROLE_BUSINESS_SUPPORT"
export const USER_ROLE_LOGISTIC_COORDINATOR = "USER_ROLE_LOGISTIC_COORDINATOR"
export const USER_ROLE_WAREHOUSE_STAFF = "USER_ROLE_WAREHOUSE_STAFF"
export const USER_ROLE_DELIVERY_STAFF = "USER_ROLE_DELIVERY_STAFF"
export const USER_ROLE_SUPERADMIN = "USER_ROLE_SUPERADMIN"

export const USER_ROLES = [
    USER_ROLE_BUSINESS_SUPPORT,
    USER_ROLE_DELIVERY_STAFF,
    USER_ROLE_LOGISTIC_COORDINATOR,
    USER_ROLE_RELATIONSHIP_OFFICE,
    USER_ROLE_RELATIONSHIP_OFFICE_COORDINATOR,
    USER_ROLE_SALES_OPERATIONAL_CO_LEAD,
    USER_ROLE_SALES_OPERATIONAL_LEAD,
    USER_ROLE_TECHNICAL_SUPPORT,
    USER_ROLE_TECHNICAL_SUPPORT_COORDINATOR,
    USER_ROLE_WAREHOUSE_STAFF,
    USER_ROLE_SUPERADMIN
]