export const CLEAR_USER_DATA = "CLEAR_USER_DATA";
export const USER_STATE_CHANGE = "USER_STATE_CHANGE";
export const USER_PRIVILEGES_STATE_CHANGE = "USER_PRIVILEGES_STATE_CHANGE";
export const USER_ACCOUNT_ROLES_STATE_CHANGE = "USER_ACCOUNT_ROLES_STATE_CHANGE";

export const CLEAR_ORDER_DATA = "CLEAR_ORDER_DATA";
export const NEW_ORDER_STATE_OVERHAUL = "NEW_ORDER_STATE_OVERHAUL";
export const NEW_REQUEST_ORDER_STATE_UPDATE = "NEW_REQUEST_ORDER_STATE_UPDATE";
export const ORDER_DOCTORS_STATE_OVERHAUL = "ORDER_DOCTORS_STATE_OVERHAUL";
export const ORDER_HOSPITALS_STATE_OVERHAUL = "ORDER_HOSPITALS_STATE_OVERHAUL";
export const ORDER_WAREHOUSE_STORAGES_STATE_OVERHAUL = "ORDER_WAREHOUSE_STORAGES_STATE_OVERHAUL";