export const CLEAR_USER_DATA = "CLEAR_USER_DATA";
export const USER_STATE_CHANGE = "USER_STATE_CHANGE";

export const CLEAR_ORDER_DATA = "CLEAR_ORDER_DATA";
export const NEW_ORDER_STATE_OVERHAUL = "NEW_ORDER_STATE_OVERHAUL";